# Book settings
title: "rossmo et ridgway : an application of rossmo's formula"
author: Tim

repository: 
  url: "https://github.com/aufdemarbeitsmarkt/rossmo_et_ridgway"

execute:
  execute_notebooks: cache
  timeout: 180

sphinx:
  config:
    execution_show_tb: True